webrecorder/wabac.js

package.json, yarn.lock
Quick dependency fix. 
If there is an obvious reason I'm missing to use `github:foliojs/brotli.js` instead of [the version currently available on `npm`](https://www.npmjs.com/package/brotli) (which stems from the same GitHub repository), it would be great to document it.
Cheers.
=> Replaced ref to `github:foliojs/brotli.js` by latest npm version in `package.json`

src/rewrite/html.js
Considering following case:
```html
<script type="text/javascript">console.log("hello world!")</script>
<script type="text/json" id="myJson">{"json":true}</script>
<script type="text/javascript">console.log(document.getElementById('myJson').textContent)</script>
```
When parsing the first `script` element, `scriptRW` are setted to `script`; when it comes the second, it never set back to empty string.
It was to process unwanted result for any script block which `type` setted and not javascript.
=> Set `scriptRW` back to empty string when unable to determine script type

src/wacz/waczimporter.js
More tolerant for WACZ files that are missing the profile..
=> wacz loading: treat missing profiles as default single-wacz

src/collection.js, src/response.js
Resolves #133 
I'm not sure how wise it is to always override this based on `request.destination` (rather than as an ExtraConfig option) but this works! 
Screenshot:
=> fix: show attachments inline based on request.destination

package.json, src/rewrite/html.js, test/rewriteHTML.js
fixes webrecorder/archiveweb.page#178
bump to 2.16.9
=> fix document.close() inject to only be used for JS scripts

src/api.js, src/archivedb.js
Resolves #143 
Returns an array of timestamps that looks like this: 
Had to pass `url` as a parameter because the `/`s where causing parse failures.
=> API for getting Timestamps from pages

src/cdxloader.js, src/warcloader.js
- in WARC loader, properly load non-GET method even if body is empty.
- in CDX indexer, ensure empty non-GET method goes through proper canonicalization even if body is empty.
=> properly index POST requests with empty bodies as POST requests

src/collection.js, src/notfound.js
Previously, an HTML 404 page was returned for all not found errors. This adjusts that to return a potentially more type-appropriate error message, which may improve fidelity (eg. reduce syntax errors where HTML is parsed as JSON) by returning error messages in appropriate type. Thus far, HTML, CSS, JS and JSON error messages are supported.
Also - tweak the about:blank response to make it more compatible, removing `<!doctype html>` which is not part of standard about:blank
=> Improved 'not found' message based on resource type

src/liveproxy.ts, src/notfound.ts, src/rewrite/html.ts, test/rewriteHTML.ts
- add custom error page for live proxy errors for >400 (except 404) status responses
- error page sends a 'live-proxy-url-error' from page when loaded
- add option to send messages when proxy POST request fail, or when rate limited, if messageOnProxyErrors is set, sending 'rate-limited' and 'post-request-failed' from the service worker
rewrite:
- use if_ / fr_/ modifiers for iframes / frames again to help differentiate frames for live proxy
- add tests for if_ frame rewrite
=> live proxy improvements error reporting improvements

package.json, src/collection.ts, src/request.ts, src/wacz/multiwacz.ts
- Don't redirect in proxy origin mode when replaying WACZ
- Fixes 'proxy origin' (non-rewriting mode) replay, as used in: https://github.com/ikreymer/proxy-wabac
- bump to 2.20.1
=> Fixes for 'proxy' mode

package.json, src/collection.ts, src/index.ts, src/response.ts, src/rewrite/dsruleset.ts, src/rewrite/index.ts, test/rewriteVideo.ts, yarn.lock
- New fuzzy matching rules for FB, matching and rewriting embedded DASH (again)
- New ruleset: range-as-query args configured per domain, allows lookup of range requests set via query args
- APIs: add hasRangeAsQuery() and removeRangeAsQuery() to detect if URL has range embedded in the query args
- Part of fix for webrecorder/archiveweb.page#272
=> Fix for FB video replay

package.json, src/rewrite/dsruleset.ts
Follow-up to #212, additional fixes to embedded dash manifests:
- better search for end tag
- don't attempt rewrite if end tag not found
- bump to 2.20.5
=> rewrite: fix new FB dash parsing

package.json, src/collection.ts, yarn.lock
update to wombat 3.8.7 for corresponding fix
bump to 2.20.6
=> remove btoa() from localStorage, just encode string as json, 

package.json, src/wacz/ziprangereader.ts
Fix regression introduced during TypeScript conversion
- remove unneeded size var that default to 0, prevented a full load since never null
- use length instead of size (initial state set to null) in base class
- fixes #215
=> Fix for nested multi WACZ loading

src/response.ts, src/rewrite/html.ts, src/utils.ts
- detect if <meta charset='utf-8'> is set and switch parsing to utf-8, if not already
- parse first 512 of html buffer first in case <meta charset> is present in the beginning, so that subsequent parsing may use the correct encoding
- fixes #218
=> better detection of charset utf-8 in html:

package.json, src/api.ts, src/types.ts, src/wacz/multiwacz.ts, src/wacz/waczfile.ts, src/wacz/waczimporter.ts, yarn.lock
When dealing with multi-WACZ collection specified via json manifest, loading all WACZ files on init becomes unscalable.
This PR provides an initial optimization to:
- Avoid load all WACZ files on load for multi WACZ, if pagesQueryUrl is provided.
- Support for querying pages for exact match 'url' param via pagesQueryUrl to determine if pages exist, and which WACZ files they're in, and only loading those.
- Support for preloadResources to automatically load a subset of WACZ files (such as those that have no pages, for patches).
- Handling of crawl id in pages and wacz files to build a mapping of seed-page-for-crawl to always load the WACZ that contains seed pages.
- Fallback to load all WACZs if < 3 files total.
- Dynamic search interface via pagesQueryUrl with 'search', 'page', 'pageSize' …
=> Support for dynamic page loading + multi WACZ loading optimization

package.json, src/wacz/multiwacz.ts
- also lookup corresponding page for 'urn:<type>:<url>' requests, assume <url> is a page
- pages query: don't add null filenames if page has no filename
- bump to 2.21.1
=> page optimization fixes: lookup urn:<type>:<url> request for corresponding page

package.json, src/blockloaders.ts, src/ipfs.ts, src/wacz/ziprangereader.ts
- avoid extra getLength() call if loader supports negative ranges from end!
- add getNegativeRange(), which will use negative range lookup if supported - so far, only FetchRangeLoader
- otherwise, call getLength() to compute offset from end
- use getNegativeRange() in ZipRangeReader for loading WACZ files
- bump to 2.21.3
=> support negative offset range for FetchRangeLoader:

.github/workflows/make-draft-release.yaml, package.json, src/archivedb.ts, src/blockloaders.ts, src/collection.ts, src/request.ts, src/rewrite/html.ts, src/rewrite/index.ts, src/swmain.ts, src/types.ts, src/wacz/multiwacz.ts, test/rewriteHTML.ts
Fix / improve support for proxy origin mode:
- proxy mode rewriting applied, ensure headers and links to proxy origin are rewritten to local origin
- normal rewriting more for iframes
- support for banner, specified via extraConfig.proxyBannerUrl
rewriting: use more specific modifier to assist proxy origin rewriting for links, iframes, add ln_ modifier for internal use.
MultiWACZ + proxy origin tweaks:
- if page not found and has www., try without www.
- keep track of referrer to determine page for MultiWACZ
- if lookup from multiple WACZs, find best response by timestamp distance correctly.
- as fallback, try all WACZ files, fix nested MultiWACZ replay
ci: add draft release ci action
bump to 2.22.0-beta.0
=> Improved support for proxy origin replay mode

package.json, src/collection.ts, src/request.ts, src/rewrite/index.ts, src/rewrite/proxyinject.ts, src/swmain.ts, src/types.ts, webpack.config.cjs
Support selective rewriting of all a.href links for subdomain given a TLD, mapping proxyTLD -> localTLD
Proxy Injection (mini-wombat):
- add src/rewrite/proxyinject.ts to be build into wombatProxy.js, injected into proxy mode replay
- support a.href rewriting for new links added (via dom override and window.open)
- rewriting of iframe.src to direct rewriting at closest timestamp, using dom override
bump to 2.22.3
=> Proxy TLD Rewriting + Proxy 'mini-wombat' banner inject

package.json, src/rewrite/html.ts, src/rewrite/proxyinject.ts, src/wacz/multiwacz.ts
- attempt to rewrite links in html via regex
- simplify proxyhtmlrewriter to avoid extra attr manipulation
- add insertAdjacentHTML rewriting, DocumentFragment.append / prepend rewriting (via regex)
- don't set noFuzzyMatch flag for proxy mode lookup, as it's initial, not fallback
- bump to 2.22.4
=> More proxy rewriting fixes

src/swmain.ts
This ensures that all properties of the request, aside from the url, are carried over from the original request.
This is necessary for certain features of GovArchive.us, specifically usage data collection via Plausible.
=> Pass existing request parameters to `Request` constructor init parameter

src/swmain.ts, src/utils/staticPathProxy.ts, tsconfig.eslint.json, webpack.config.cjs
Closes #233 
Updates include: 
Manual testing:
1. Go to one of the govarchive.us sites (I used https://cdc.govarchive.us/)
2. Open Chrome Devtools (there's likely a way to do this with FF too, I haven't tested)
3. In the **Application** tab, navigate to the **Service Workers** section and click the <kbd>Unregister</kbd> button for the service worker for the site you're on
4. Under the **Source** header, click the **sw.js** link to go to the service worker script in the **Sources** tab
5. Open the sidebar and go to the **Overrides** tab — this may be hidden in the right chevron menu <kbd>»</kbd>
6. Check **Enable Local Overrides**
7. In your terminal, build wabac.js with `yarn build` locally, and copy the contents of `dist/sw.js`
8. Back in the browser, click anywhere in the file contents …
=> Get static proxy working for non-GET requests

package.json, src/fuzzymatcher.ts
- allow negative totals to be accepted
- just weigh non-200 responses linearly, subtract from total score
bump version to 2.22.8
=> fuzzymatching:

package.json, src/swmain.ts
- in this case, assume using a shared path with existing web server
- assume the top-frame is provided by existing web server, just do defaultFetch()
- also pass through any unknown requests (not valid wburl) to existing web server, instead of returning 404
- bump to 2.22.9
=> replay: add top frame passthrough when using no replay suffix is set (for pywb support)

package.json, src/collection.ts, src/rewrite/index.ts, yarn.lock
don't prepend rewrite code for esm worker module at all
requires wombat 2.8.9
bump to 2.22.11
(fixes replay of gallery on: https://enfoco.org/nueva-luz-archive/)
=> rewrite: support worker esm module with wkrm_: 

src/collection.ts, src/response.ts, src/swmain.ts, src/utils.ts
- ensure csp policy is always set, even for default fetch / fallthrough responses, unless in proxy origin mode
- if no csp policy is found in handleFetch response, add default csp
- if fail to set csp, make a copy of response
=> Ensure CSP is always set

package.json, src/collection.ts, src/notfound.ts, src/request.ts, src/rewrite/html.ts, src/swmain.ts, src/utils.ts, yarn.lock
not-found response cleanup:
- remove old notFound, use type-specific notFound with custom message support
- add csp to not-found response
no-collection redirect:
- catch URL requests that are missing a collection, eg. <current origin>/newPath with referer <current origin>/collection/<ts>mp_/<replay url>/path and redirect to <current origin>/collection/<ts>mp_/<replay url>/newPath
- shouldn't happen if initial rewrite is correct, but will catch these to avoid unnecessary fallthrough
rewrite: fix meta refresh with no url= rewrite
deps: bump wombat to 3.8.11
=> Not Found Response / No Collection Redirect

package.json, src/collection.ts, src/response.ts, src/rewrite/index.ts, src/swmain.ts
but keep key hardening in place:
- ensure csp added to all error pages
- ensure 'not found' page served when loading off domain, if referrer is replay
- ensure redirect back to collection for collecton-less replay
- rewrite Referrer-Policy to avoid it being altered
- prefix 'referrer-policy' header to prevent it from being overwritten in replay bump to 2.22.14
=> undo more aggressive csp check everywhere as it breaks embeds

package.json, src/index.ts, src/rewrite/index.ts, src/swmain.ts, src/utils.ts, test/rewriteHTML.ts
proxy paths:
- treat proxy allow paths as prefixes:
- add 'allowProxyPrefix' to query params, to allow custom prefixes
backslash:
- rewrite '\' for URLs starting with '\' (and ignore '\/')
- add tests to ensure '\path\file.html' treated same as '/path/file.html'
bump to 2.22.17
=> allow proxy paths + backslash rewriting

src/utils.ts
Follow-up to #246, Firefox still requires CSP policy for the service worker itself to be allowed to load iframes controlled by the service worker.
Seems like incorrect interpretation of 'frame-src', but need it to fix iframe replay in FF.
=> csp tweak: include SW path (without query) in CSP

package.json, src/blockloaders.ts, src/loaders.ts
- avoid negative range request if -N is less than full length of file, just load full file instead
- if range requests not supported, but file is small enough (<25MiB, same as full download size), just load entire wacz into memory and do random access from arraybuffer
- blockloaders: add getFullBuffer() to return full buffer, if available, for cacheing
- bump to 2.23.0
=> fix small file loading / range request issues:

package.json, src/blockloaders.ts, src/loaders.ts, src/types.ts, src/utils.ts, src/wacz/certutils.ts, src/wacz/multiwacz.ts, src/wacz/waczloader.ts
- Don't reload every multiWACZ collection JSON source on service worker init
- Load known multiwacz settings from metadata instead
- Do an async background check of multiWACZ collections, no more than one per day, and prune when JSON file can no longer be accessed.
- Catch fetch errors that are due to CORS and treat same as access denied, allow multiple retries for loading WACZs in case of etch errors
- Add typing for multiWACZ JSON
=> Optimize loading + periodic delete of expired multiwaczs

src/rewrite/html.ts, test/rewriteHTML.ts
ensure rewriting even when 'URL=' is missing in meta refresh
=> rewrite: adjust meta refresh to make 'url=' optional

src/rewrite/dsruleset.ts
- ensure additional rewriting is also padded in the same way as in #248 with spaces
- export MediaSource override string, switch to use defineProperty for override
=> rewrite padding: follow up to #248, also pad FB dash/hls rewriting

src/baseparser.ts, src/collection.ts, src/response.ts, src/rewrite/dsruleset.ts, src/rewrite/rewriteVideo.ts, src/types.ts
- add ExtraOpts type covering known types used in AWP and browsertrix-crawler
- add disableMSE check to proxy mode replay
=> typing: add typing for extraOpts included in WARC-JSON-Metadata

package.json, src/rewrite/jsrewriter.ts, test/rewriteJS.ts
- js: add global 'class NAME' as 'self.NAME = NAME' in non-esm scripts, follow-up to #128, support for top-level globals
- js: don't rewrite 'location => ' construction, add check for '>' after '='
bump to 2.23.7
=> JS rewrite fixes: top-level globals + location rewrite

package.json, src/rewrite/jsrewriter.ts, test/rewriteJS.ts
- additional rewrite fixes with negative lookbehind (now supported in all browsers)
- fixes replay where 'static eval' as well as 'function eval' and '} eval' are skipped
=> rewrite: fix eval() rewriting

src/rewrite/html.ts
- treat as UTF-8 if reencoded
- don't check for charset if BOM already found / already UTF-8
=> html charset detection follow up to #278:

package.json, src/rewrite/html.ts, test/rewriteHTML.ts, yarn.lock
- fix rewrite <embed> tag
- add tests to ensure correct rewrite
- update to wombat 3.9.1 to fix document.write() rewriting check bump to 2.24.1
=> rewrite: embed rewrite fix + wombat fix:
